name: cleanup pr branch
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jasontedor/cleanup-pr-branch-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
